// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  challengeId: __t.string().name("challenge_id"),
  squadSize: __t.u8().name("squad_size"),
  teamName: __t.string().name("team_name"),
  players: __t.array(__t.string()),
  timeMs: __t.u64().name("time_ms"),
  createdAt: __t.timestamp().name("created_at"),
});
