// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CleanupTimer = __t.object("CleanupTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CleanupTimer = __Infer<typeof CleanupTimer>;

export const Conn = __t.object("Conn", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
});
export type Conn = __Infer<typeof Conn>;

export const Input = __t.object("Input", {
  identity: __t.identity(),
  code: __t.string(),
  teamId: __t.u64(),
  roles: __t.array(__t.string()),
  get inputs() {
    return __t.array(RoleInput);
  },
});
export type Input = __Infer<typeof Input>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  code: __t.string(),
  name: __t.string(),
  teamId: __t.u64(),
  roles: __t.array(__t.string()),
  ready: __t.bool(),
  solo: __t.bool(),
  joinedSeq: __t.u64(),
  lastSeenMicros: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const RoleInput = __t.object("RoleInput", {
  f: __t.f32(),
  s: __t.f32(),
  a: __t.bool(),
  b: __t.bool(),
  q: __t.bool(),
  e: __t.bool(),
  lx: __t.f32(),
  ly: __t.f32(),
});
export type RoleInput = __Infer<typeof RoleInput>;

export const Room = __t.object("Room", {
  code: __t.string(),
  phase: __t.string(),
  challengeId: __t.string(),
  round: __t.u32(),
  startAtMicros: __t.u64(),
  nowMicros: __t.u64(),
  nextTeamId: __t.u32(),
  nextPlayerSeq: __t.u64(),
});
export type Room = __Infer<typeof Room>;

export const RoundTimer = __t.object("RoundTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  code: __t.string(),
  round: __t.u32(),
  kind: __t.string(),
});
export type RoundTimer = __Infer<typeof RoundTimer>;

export const Score = __t.object("Score", {
  id: __t.u64(),
  challengeId: __t.string(),
  teamName: __t.string(),
  players: __t.array(__t.string()),
  timeMs: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Score = __Infer<typeof Score>;

export const Snapshot = __t.object("Snapshot", {
  teamId: __t.u64(),
  code: __t.string(),
  recvMicros: __t.u64(),
  p: __t.array(__t.f32()),
  props: __t.array(__t.f32()),
  yaw: __t.f32(),
  pitch: __t.f32(),
  timer: __t.f32(),
  fallen: __t.bool(),
  score: __t.u32(),
  ev: __t.string(),
  msg: __t.option(__t.string()),
});
export type Snapshot = __Infer<typeof Snapshot>;

export const Squad = __t.object("Squad", {
  code: __t.string(),
  size: __t.u8(),
});
export type Squad = __Infer<typeof Squad>;

export const Team = __t.object("Team", {
  id: __t.u64(),
  code: __t.string(),
  name: __t.string(),
  color: __t.string(),
  hostId: __t.option(__t.identity()),
  finishMs: __t.option(__t.u64()),
});
export type Team = __Infer<typeof Team>;

