// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  teamId: __t.u64().primaryKey().name("team_id"),
  code: __t.string(),
  recvMicros: __t.u64().name("recv_micros"),
  p: __t.array(__t.f32()),
  props: __t.array(__t.f32()),
  yaw: __t.f32(),
  pitch: __t.f32(),
  timer: __t.f32(),
  fallen: __t.bool(),
  score: __t.u32(),
  ev: __t.string(),
  msg: __t.option(__t.string()),
  round: __t.option(__t.u32()),
  sequence: __t.option(__t.u64()),
});
