// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RoleInput,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  code: __t.string(),
  teamId: __t.u64().name("team_id"),
  roles: __t.array(__t.string()),
  get inputs() {
    return __t.array(RoleInput);
  },
  recvMicros: __t.option(__t.u64()).name("recv_micros"),
});
