// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  code: __t.string(),
  name: __t.string(),
  teamId: __t.u64().name("team_id"),
  roles: __t.array(__t.string()),
  ready: __t.bool(),
  solo: __t.bool(),
  joinedSeq: __t.u64().name("joined_seq"),
  lastSeenMicros: __t.u64().name("last_seen_micros"),
  hostEligible: __t.option(__t.bool()).name("host_eligible"),
});
