// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  phase: __t.string(),
  challengeId: __t.string().name("challenge_id"),
  round: __t.u32(),
  startAtMicros: __t.u64().name("start_at_micros"),
  nowMicros: __t.u64().name("now_micros"),
  nextTeamId: __t.u32().name("next_team_id"),
  nextPlayerSeq: __t.u64().name("next_player_seq"),
  leaderId: __t.option(__t.identity()).name("leader_id"),
});
